---
application:
  name: Theatre of Mind Bot
  version: 1.0-SNAPSHOT


quarkus:
  oidc:
    application-type: web-app
    authentication:
      cookie-path: /
      user-info-required: true

    logout:
      path: /logout
      post-logout-path: /ui
      backchannel:
        path: /back-channel-logout

    roles:
      source: userinfo
      role-claim-path: "realm_access/roles"

  datasource:
    reactive:
      mysql:
        ssl-mode: preferred

  http:
    proxy:
      proxy-address-forwarding: true
      allow-forwarded: true
      enable-forwarded-host: true
      forwarded-host-header: X-ORIGINAL-HOST
    cors:
      ~: true
      origins: http.//localhost:8080
      methods: GET,PUT,POST,HEAD
    auth:
      permission:
        ui:
          paths: /ui/*
          policy: ui
        admin:
          paths: /ui/admin/*
          policy: admin
        api:
          paths: /api/*
          policy: api
        observability:
          paths: /q/*
          policy: observability
      policy:
        ui:
          roles-allowed: user
        admin:
          roles-allowed: admin
        api:
          roles-allowed: api
        observability:
          roles-allowed: metrics
    access-log:
      enabled: true
      exclude-pattern: "/q/healthz/*"
    record-request-start-time: true
    enable-compression: true
    enable-decompression: true
  health:
    openapi:
      included: true

  smallrye-graphql:
    metrics:
      enabled: true
    tracing:
      enabled: true
    validation:
      enabled: true
    events:
      enabled: true

  log:
    console:
      json: true
      stderr: true
      async:
        ~: true
        queue-length: 256
        overflow: discard
    min-level: TRACE
    level: INFO
    category:
      "de.kaiserpfalzedv":
        level: TRACE
    metrics:
      enabled: true

  locales:
    - de-DE
    - de-AU
    - de-CH
    - en-UK
    - en-US
  default-locale: de-DE

resteasy:
  role:
    based:
      security: true

org:
  eclipse:
    microprofile:
      rest:
        client:
          propagateHeaders: Authorization

"%dev":
  quarkus:
    log:
      console:
        json: false