---
application:
  name: Theatre of Mind Bot
  version: 1.0-SNAPSHOT
  http:
    ui-base: /ui/


quarkus:
  oidc:
    application-type: web-app
    authentication:
      cookie-path: /
      user-info-required: true
    logout:
      path: /logout
      post-logout-path: /ui/
      backchannel:
        path: /back-channel-logout
    roles:
      source: userinfo
      role-claim-path: "realm_access/roles"
  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        realm-name: Technical Users
        users:
          klenkes: klenkes
          prometheus: Maica7biegheishe
          check: eeneila7UGohz6Ia
        roles:
          klenkes: user,admin,api,operator
          prometheus: metrics
          check: checks

  datasource:
    jdbc:
      ~: true
      enable-metrics: true
    health:
      enabled: true
    metrics:
      enabled: true
  liquibase:
    migrate-at-start: true
    validate-on-migrate: true

  http:
    proxy:
      proxy-address-forwarding: true
      allow-forwarded: true
      enable-forwarded-host: true
      forwarded-host-header: X-ORIGINAL-HOST
    cors:
      ~: true
      origins: http://localhost:8080
      methods: GET,PUT,POST,HEAD
    auth:
      permission:
        ui:
          paths: "/ui/*"
          policy: ui
          methods: GET, POST, PUT, HEAD
        free:
          paths: "/ui/free/*"
          policy: permit
          methods: GET, POST, PUT, HEAD
        admin:
          paths: "/ui/admin/*"
          policy: admin
          methods: GET, POST, PUT, HEAD
        api:
          paths: /api/*
          policy: api
        operator:
          paths: /q
          policy: operator
          methods: GET, POST, PUT, HEAD
          auth-mechanism: basic
        checks:
          paths: /q/health,/q/health/*
          policy: checks
          methods: GET
          auth-mechanism: basic
        metrics:
          paths: /q/metrics
          policy: metrics
          methods: GET
          auth-mechanism: basic
      policy:
        ui:
          roles-allowed: user
        api:
          roles-allowed: user,admin,api,operator
        admin:
          roles-allowed: admin
        operator:
          roles-allowed: operator
        checks:
          roles-allowed: checks,operator
        metrics:
          roles-allowed: metrics,operator
    access-log:
      enabled: true
      exclude-pattern: "/q/health*"
    record-request-start-time: true
    enable-compression: false
    enable-decompression: false

  health:
    openapi:
      included: true

  log:
    console:
      json: true
      stderr: true
      async:
        ~: true
        queue-length: 256
        overflow: discard
    min-level: TRACE
    level: INFO
    category:
      "de.kaiserpfalzedv":
        level: TRACE
    metrics:
      enabled: true

  locales:
    - de-DE
    - de-AU
    - de-CH
    - en-UK
    - en-US
  default-locale: de-DE

resteasy:
  role:
    based:
      security: true

org:
  eclipse:
    microprofile:
      rest:
        client:
          propagateHeaders: Authorization

"%dev":
  quarkus:
    log:
      console:
        json: false