---
application:
  name: Theatre of Mind Bot
  version: 1.0-SNAPSHOT
  http:
    ui-base: /dashboard


quarkus:
  oidc:
    enabled: false
    application-type: web-app
    authentication:
      cookie-path: /
      user-info-required: true
    logout:
      path: /oidc-logout
      post-logout-path: /dashboard
      backchannel:
        path: /back-channel-logout
    roles:
      role-claim-path: "groups"
    token-state-manager:
      split-tokens: true
  security:
    users:
      embedded:
        enabled: false
        plain-text: true
        realm-name: Technical Users
        users:
          klenkes: klenkes
          prometheus: Maica7biegheishe
          check: eeneila7UGohz6Ia
        roles:
          klenkes: user,admin,api,operator
          prometheus: metrics
          check: checks

  datasource:
    jdbc:
      ~: true
      enable-metrics: true
    health:
      enabled: true
    metrics:
      enabled: true
  liquibase:
    migrate-at-start: true
    validate-on-migrate: true

  http:
    proxy:
      proxy-address-forwarding: true
      allow-forwarded: true
      enable-forwarded-host: true
      forwarded-host-header: X-ORIGINAL-HOST

    access-log:
      enabled: true
      exclude-pattern: "/q/health.*"
    record-request-start-time: true
    enable-compression: false
    enable-decompression: false

  resteasy:
    metrics:
      enabled: true

  health:
    openapi:
      included: true

  log:
    console:
      json: true
      stderr: true
      async:
        ~: false
        queue-length: 256
        overflow: discard
    min-level: TRACE
    level: INFO
    category:
      "de.kaiserpfalzedv":
        level: TRACE
      "com.vaadin":
        level: TRACE
    metrics:
      enabled: true

  locales:
    - de-DE
    - de-AU
    - de-CH
    - en-UK
    - en-US
  default-locale: de-DE

resteasy:
  role:
    based:
      security: true

org:
  eclipse:
    microprofile:
      rest:
        client:
          propagateHeaders: Authorization

"%dev":
  quarkus:
    log:
      console:
        json: false